
const NOT_IN_TEL_OR_PASS = "手机号码或密码未输入"
const NOT_IN_USERNAME_OR_PASS = "用户名或密码未输入"
const NOT_IN_BOAT_OR_PASS = "船名或密码未输入"
const USER_NOT_EXIT = "用户不存在"
const USER_EXIT = "用户存在"
const REGIST_INFO_ERROR = "注册信息有错误，请核对"
const FORGET_INFO_ERROR = "邮箱出错"
const FORGET_MAIL_INFO_ERROR = "发送邮件失败"


module.exports = {
    NOT_IN_TEL_OR_PASS:NOT_IN_TEL_OR_PASS,
    NOT_IN_USERNAME_OR_PASS: NOT_IN_USERNAME_OR_PASS,
    NOT_IN_BOAT_OR_PASS:NOT_IN_BOAT_OR_PASS,
    USER_NOT_EXIT:USER_NOT_EXIT,
    REGIST_INFO_ERROR:REGIST_INFO_ERROR,
    FORGET_INFO_ERROR:FORGET_INFO_ERROR,
    FORGET_MAIL_INFO_ERROR:FORGET_MAIL_INFO_ERROR,
    USER_EXIT:USER_EXIT
}